run:
  timeout: 5m
  go: "1.23"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  errcheck:
    check-type-assertions: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
