//go:build linux

package ebpf

import (
	"context"
	"debug/elf"
	"errors"
	"fmt"
	"log/slog"

	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
)

// Probe manages BPF program loading, uprobe attachment, and event reading.
type Probe struct {
	objs      *querytapObjects // generated by bpf2go
	uprobe    link.Link
	uretprobe link.Link
	reader    *ringbuf.Reader
	logger    *slog.Logger
}

// dispatchCommandSymbol is the C++ mangled name of dispatch_command in mysqld.
// MySQL 8.x: _Z16dispatch_commandP3THDPK8COM_DATA19enum_server_command
// We search for it dynamically since the exact mangling can vary.
const dispatchCommandSymbol = "_Z16dispatch_commandP3THDPK8COM_DATA19enum_server_command"

// findDispatchCommandSymbol searches for the dispatch_command symbol in the binary.
// It tries the C++ mangled name first, then falls back to the plain C name.
func findDispatchCommandSymbol(binaryPath string) (string, error) {
	f, err := elf.Open(binaryPath)
	if err != nil {
		return "", fmt.Errorf("opening ELF: %w", err)
	}
	defer f.Close()

	// Check dynamic symbols first (.dynsym), then regular symbols (.symtab)
	for _, getter := range []func() ([]elf.Symbol, error){f.DynamicSymbols, f.Symbols} {
		syms, err := getter()
		if err != nil {
			continue
		}
		for _, s := range syms {
			// Match the full mangled name or the plain name
			if s.Name == dispatchCommandSymbol || s.Name == "dispatch_command" {
				return s.Name, nil
			}
		}
	}

	return "", fmt.Errorf("symbol dispatch_command (or mangled variant) not found in %s", binaryPath)
}

// NewProbe loads BPF objects and attaches uprobes to the mysqld binary at
// binaryPath. The caller must call Close when done.
func NewProbe(binaryPath string, logger *slog.Logger) (*Probe, error) {
	symbol, err := findDispatchCommandSymbol(binaryPath)
	if err != nil {
		return nil, fmt.Errorf("finding symbol: %w", err)
	}
	logger.Info("found dispatch_command symbol", "symbol", symbol)

	var objs querytapObjects
	if err := loadQuerytapObjects(&objs, nil); err != nil {
		return nil, fmt.Errorf("loading BPF objects: %w", err)
	}

	ex, err := link.OpenExecutable(binaryPath)
	if err != nil {
		objs.Close()
		return nil, fmt.Errorf("opening executable %q: %w", binaryPath, err)
	}

	up, err := ex.Uprobe(symbol, objs.UprobeDispatchCommand, nil)
	if err != nil {
		objs.Close()
		return nil, fmt.Errorf("attaching uprobe: %w", err)
	}

	uret, err := ex.Uretprobe(symbol, objs.UretprobeDispatchCommand, nil)
	if err != nil {
		up.Close()
		objs.Close()
		return nil, fmt.Errorf("attaching uretprobe: %w", err)
	}

	rd, err := ringbuf.NewReader(objs.Events)
	if err != nil {
		uret.Close()
		up.Close()
		objs.Close()
		return nil, fmt.Errorf("creating ring buffer reader: %w", err)
	}

	logger.Info("BPF probes attached",
		"binary", binaryPath,
		"symbol", symbol,
	)

	return &Probe{
		objs:      &objs,
		uprobe:    up,
		uretprobe: uret,
		reader:    rd,
		logger:    logger,
	}, nil
}

// ReadEvents reads events from the ring buffer and sends them to ch.
// Blocks until ctx is cancelled. Returns nil on clean shutdown.
func (p *Probe) ReadEvents(ctx context.Context, ch chan<- Event) error {
	// Close the reader when context is cancelled to unblock Read().
	go func() {
		<-ctx.Done()
		p.reader.Close()
	}()

	for {
		record, err := p.reader.Read()
		if err != nil {
			if errors.Is(err, ringbuf.ErrClosed) {
				return nil
			}
			p.logger.Warn("ring buffer read error", "error", err)
			continue
		}

		evt, err := DecodeEvent(record.RawSample)
		if err != nil {
			p.logger.Warn("event decode error", "error", err)
			continue
		}

		select {
		case ch <- evt:
		case <-ctx.Done():
			return nil
		}
	}
}

// Close detaches probes and releases all BPF resources.
// Resources are closed in reverse order of creation.
func (p *Probe) Close() error {
	var errs []error

	if p.reader != nil {
		if err := p.reader.Close(); err != nil && !errors.Is(err, ringbuf.ErrClosed) {
			errs = append(errs, fmt.Errorf("closing reader: %w", err))
		}
	}
	if p.uretprobe != nil {
		if err := p.uretprobe.Close(); err != nil {
			errs = append(errs, fmt.Errorf("closing uretprobe: %w", err))
		}
	}
	if p.uprobe != nil {
		if err := p.uprobe.Close(); err != nil {
			errs = append(errs, fmt.Errorf("closing uprobe: %w", err))
		}
	}
	if p.objs != nil {
		if err := p.objs.Close(); err != nil {
			errs = append(errs, fmt.Errorf("closing BPF objects: %w", err))
		}
	}

	return errors.Join(errs...)
}
